### ISSUE TITLE
Hodnocení úkolu č. 2

### ISSUE THREAD

**Issue by tommander** [KaterinaZlesakova/PROJEKT-Vizitka#1]
1/ Chybí změna barvy tlačítka Twitter/Facebook po najetí myší (v CSS je na to i definovaná barva)

Drobnost/ To odsazení vizitky od horního okraje o 150 px bych doporučoval spíše řešit přímo na prvku **div** místo **body**, věděla bys, jak to upravit? :) Takhle je na úzkem monitoru ta vizitka odsazená o 150 px také z levé a pravé strany, byť na většině monitorů to nevadí, ale pozor později, když budeš řešit mobilní design.

Jinak je to super a dle zadání, kód je přehledný, funguje to, jak má, nic neodskakuje, takže dobrá práce, chválím a gratuluji :) A až budeš mít opraven bod 1 (popř. i tu drobnost), tak to bude _perfektní_ :)

**Comment by KaterinaZlesakova** [comment]
1) Ohledně změny barvy tlačítek po najetí se omlouvám, to jsem nějak přehlédla a úplně vypustila, ale je to již opraveno a mělo by to fungovat. 
2) To odsazení jsem snad už také napravila.

Díky. :-)

**Comment by tommander** [comment]
Perfektní! :) Dobrá práce
